[tool.poetry]
name = "ctf_evals_core"
version = "0.1.0"
description = ""
authors = ["Will.Payne <Will.Payne@dsit.gov.uk>"]
readme = "README.md"
packages = [
  {include = "ctf_evals_core", from = "src"},
  {include = "ctf_evals_tests", from = "src"},
]

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.1"
pytest = "^8.1.1"
ruamel-yaml = "^0.18.6"
inspect-ai = {git = "https://github.com/UKGovernmentBEIS/inspect_ai.git"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
