[tool.poetry]
name = "ctf_evals_core"
version = "0.1.0"
description = ""
authors = ["Will.Payne <Will.Payne@dsit.gov.uk>"]
readme = "README.md"
packages = [
  {include = "ctf_evals_core", from = "src"},
  {include = "ctf_evals_tests", from = "src"},
]

[tool.poetry.scripts]
ctf_eval = "ctf_evals_core._cli.main:main"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.1"
boto3 = "^1.34.51"
pytest = "^8.1.1"
ruamel-yaml = "^0.18.6"
inspect-ai = {git = "https://github.com/UKGovernmentBEIS/inspect_ai.git"}
click = "^8.1.7"

[tool.poetry.group.dev.dependencies]
mypy = "^1.9.0"
pre-commit = "^3.6.2"
pytest = "^8.1.1"
ruff = "^0.6.0"
boto3-stubs = "^1.35.62"
types-pyyaml = "^6.0.12.20240917"

[tool.ruff.lint]
select = ["E",   # pycodestyle errors
          "W",   # pycodestyle warnings
          "F",   # flake8
          "D",   # pydocstyle
          "I",   # isort
          # "RET", # flake8-return
          # "RUF", # ruff rules
        ]
ignore = ["E203", "D10", "D203", "D212"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.poetry.plugins.inspect_ai]
ctf_evals_core = "ctf_evals_core._registry"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Ignore ctf_evals_tests since that's for people to consume not to test
# this package
[tool.pytest.ini_options]
testpaths = "tests"
